### ISSUE TITLE
Clear Pantheon Caches on Deploy

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/drupal-project#28]
Quick silver API

https://github.com/kalamuna/progenity.com/pull/535

**Comment by doostinharrell** [comment]
Yo @RobLoach!  Checkout https://github.com/pantheon-systems/example-drops-8-composer.  I've forked this and use it for all of my Pantheon.io projects.  It's got all the quicksilver bits in there as well.

Cheers!

**Comment by RobLoach** [comment]
YO DUSTIN!

Haha, funny you mention that. We've revamped a lot of this project on the example drops 8 composer project :wink: 

Much more to add! What other fancy things have you added to your base project?

**Comment by doostinharrell** [comment]
@RobLoach it's pretty much the same with some slight modification to match my process.  I need to commit back to my repo as I'm running Drupal 8.8.* which required some refactoring, among other updates. Now is probably a good time to commit those changes back.

- https://github.com/avidnewmedia/pantheon-gitlab-boilerplate

I'm also managing Drush versions via composer now and learned recently that you can reference environment name variables in the alias files themselves.  So no need to update your alias file each time a new multi dev get's spun up.

```
_local:
  root: /private/var/www/example.org/www/web
  uri: example.lndo.site

'*':
  host: appserver.${env-name}.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.drush.in
  paths:
    files: files
    drush-script: drush9
  uri: https://${env-name}-example.pantheonsite.io
  user: ${env-name}.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  ssh:
    options: '-p 2222 -o "AddressFamily inet"'
    tty: false
```
